name: CI

on: [push, pull_request]

jobs:
  windows:
    runs-on: windows-2019
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build Windows 64 bit
        run: mkdir build-win64 && cd build-win64 && cmake -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 16 2019" -A x64 .. && cmake --build . --config Release

      - name: Upload Windows 64 bit
        uses: actions/upload-artifact@v2
        with:
          name: Windows x64
          path: Release

  windows-test:
    runs-on: windows-2019
    needs: windows
    steps:
      - name: Git checkout CBA A3
        uses: actions/checkout@v2
        with:
          repository: CBATeam/CBA_A3
          path: x/cba

      - name: Download ArmaScriptCompiler artifact
        uses: actions/download-artifact@v2
        with:
          name: Windows x64

      - name: Compile CBA A3
        run: |
          xcopy x\cba\include . /s /e /h
          subst P: .
          cd P:
          cd x\cba
          ..\..\Release\ArmaScriptCompiler.exe

