name: CI

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-20.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install dependencies
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install -y gcc-11 g++-11 libtbb-dev

      - name: Build Linux 64 bit
        run: mkdir build-linux64 && cd build-linux64 && cmake .. && cmake --build . --config Release --parallel 2
        env:
          CC: gcc-11
          CXX: g++-11

      - name: Upload Linux 64 bit
        uses: actions/upload-artifact@v2
        with:
          name: Linux x64
          path: Release

  windows:
    runs-on: windows-2019
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build Windows 64 bit
        run: mkdir build-win64 && cd build-win64 && cmake -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 16 2019" -A x64 .. && cmake --build . --config Release

      - name: Upload Windows 64 bit
        uses: actions/upload-artifact@v2
        with:
          name: Windows x64
          path: Release
